name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Maven install badua-cli
        run: mvn install:install-file -DgroupId=br.usp.each.saeg -DartifactId=ba-dua-cli -Dversion=0.4.0 -Dclassifier=all -Dpackaging=jar -Dfile="./jars/ba-dua-cli-0.4.0-all.jar"
      - name: Maven install badua-agent-rt
        run: mvn install:install-file -DgroupId=br.usp.each.saeg -DartifactId=ba-dua-agent-rt -Dversion=0.4.0 -Dclassifier=all -Dpackaging=jar -Dfile="./jars/ba-dua-agent-rt-0.4.0-all.jar"
      - name: Maven verify
        run: mvn verify -P badua-coverage
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Bookkepper_report_jacoco
          path: bookkeeper-common/target/badua-xml
          if-no-files-found: error